services:
    netgen_layouts.sylius.parameters.parameter_type.taxon:
        class: Netgen\Layouts\Sylius\Parameters\ParameterType\TaxonType
        tags:
            - { name: netgen_layouts.parameter_type }

    netgen_layouts.sylius.parameters.form_mapper.taxon:
        class: Netgen\Layouts\Sylius\Parameters\Form\Mapper\TaxonMapper
        tags:
            - { name: netgen_layouts.parameter_type.form_mapper, type: sylius_taxon }
