view:
    rule_condition_view:
        value:
            sylius_channel:
                template: "@NetgenLayoutsSylius/admin/layout_resolver/condition/value/sylius_channel.html.twig"
                match:
                    rule_condition\type: sylius_channel
            sylius_locale:
                template: "@NetgenLayoutsSylius/admin/layout_resolver/condition/value/sylius_locale.html.twig"
                match:
                    rule_condition\type: sylius_locale
            sylius_resource_type:
                template: "@NetgenLayoutsSylius/admin/layout_resolver/condition/value/sylius_resource_type.html.twig"
                match:
                    rule_condition\type: sylius_resource_type
